config/routes.rb
Rails.application.routes.draw do
  resources :elec_solutions

  root "home#home"
  get "home/batteries"
  get "home/solar"
  get "home/inverters"
  get "home/install"
  get "home/inquire"
  get "home/index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/elec_solution.rb
class ElecSolution < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end


module ApplicationHelper
    include ImageHelpers
  end

app/controllers/elec_solutions_controller.rb
class ElecSolutionsController < ApplicationController
  before_action :set_elec_solution, only: %i[ show edit update destroy ]

  # GET /elec_solutions or /elec_solutions.json
  def index
    @elec_solutions = ElecSolution.all
  end

  # GET /elec_solutions/1 or /elec_solutions/1.json
  def show
  end

  # GET /elec_solutions/new
  def new
    @elec_solution = ElecSolution.new
  end

  # GET /elec_solutions/1/edit
  def edit
  end

  # POST /elec_solutions or /elec_solutions.json
  def create
    @elec_solution = ElecSolution.new(elec_solution_params)

    respond_to do |format|
      if @elec_solution.save
        format.html { redirect_to elec_solution_url(@elec_solution), notice: "Elec solution was successfully created." }
        format.json { render :show, status: :created, location: @elec_solution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elec_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elec_solutions/1 or /elec_solutions/1.json
  def update
    respond_to do |format|
      if @elec_solution.update(elec_solution_params)
        format.html { redirect_to elec_solution_url(@elec_solution), notice: "Elec solution was successfully updated." }
        format.json { render :show, status: :ok, location: @elec_solution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elec_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elec_solutions/1 or /elec_solutions/1.json
  def destroy
    @elec_solution.destroy

    respond_to do |format|
      format.html { redirect_to elec_solutions_url, notice: "Elec solution was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elec_solution
      @elec_solution = ElecSolution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def elec_solution_params
      params.require(:elec_solution).permit(:first_name, :last_name, :email, :phone, :state)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
 before_action :correct_user,only:[:edit, :destory, :update]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
   # @friend = Friend.new
   @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|

      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

   def  correct_user

    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "You are not authorized to edit" if @friend.nil?
    notice = :red
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :address, :gender, :state, :city, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end

  def batteries

  end

  def inverters

  end

  def inquire

  end

  def install

  end


  def solar

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elec_solutions_helper.rb
module ElecSolutionsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home/index_helper.rb
module Home::IndexHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/elec_solutions/_elec_solution.html.erb
<div id="<%= dom_id elec_solution %>">
  <p>
    <strong>First name:</strong>
    <%= elec_solution.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= elec_solution.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= elec_solution.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= elec_solution.phone %>
  </p>

  <p>
    <strong>State:</strong>
    <%= elec_solution.state %>
  </p>

</div>

app/views/elec_solutions/_form.html.erb
<%= form_with(model: elec_solution) do |form| %>
  <% if elec_solution.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(elec_solution.errors.count, "error") %> prohibited this elec_solution from being saved:</h2>

      <ul>
        <% elec_solution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.number_field :phone %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/elec_solutions/edit.html.erb
<h1>Edit User Account</h1>

<%= render "form", elec_solution: @elec_solution %>

<br>

<div>
  <%= link_to "Show this elec solution", @elec_solution %> |
  <%= link_to "Back to elec solutions", elec_solutions_path %>
</div>

app/views/elec_solutions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Elec solutions</h1>

<div id="elec_solutions">
  <% @elec_solutions.each do |elec_solution| %>
    <%= render elec_solution %>
    <p>
      <%= link_to "Show Profile", elec_solution %>
    </p>
  <% end %>
</div>

<%= link_to "New Profile", new_elec_solution_path %>

app/views/elec_solutions/new.html.erb
<h1>New elec solution</h1>

<%= render "form", elec_solution: @elec_solution %>

<br>

<div>
  <%= link_to "Back To User", elec_solutions_path %>
</div>

app/views/elec_solutions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @elec_solution %>

<div>
  <%= link_to "Edit User", edit_elec_solution_path(@elec_solution) %> |
  <%= link_to "Back to User", elec_solutions_path %>

  <%= button_to "Remove User", @elec_solution, method: :delete %>
</div>

app/views/friends/_form.html.erb
<div class="card">
    <div class="card-header">
<%= form_with(model: friend) do |form| %>
<% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    </div>
    <div class="card-body">
        <h5 class="card-title"></h5>
        <p class="card-text"></p>

<div class = 'container'>
  <div class = 'form-control-sm field form-group '>
    <% form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, placeholder: 'First Name' %>
  </div>

  <div class = 'form-control-sm'  >
    <% form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, placeholder: 'Last Name'%>
  </div>

  <div class = 'form-control-sm'  >
    <% form.label :email, style: "display: block" %>
    <%= form.text_field :email, placeholder: 'Email'%>
  </div>

  <div class = 'form-control-sm' >
    <% form.label :phone, style: "display: block" %>
    <%= form.number_field :phone, placeholder: 'Phone Number',type: :number %>
  </div>

  <div class = 'form-control-sm  '>
    <% form.label :address, style: "display: block" %>
    <%= form.text_field :address, placeholder: 'Address' %>
  </div>

  <div class = 'form-control-sm' >
    <% form.label :gender, style: "display: block" %>
    <%= form.text_field :gender, placeholder: 'Gender' %>
  </div>

  <div  class = 'form-control-sm' >
    <% form.label :state, style: "display: block" %>
    <%= form.text_field :state, placeholder: 'State' %>
  </div>

  <div class = 'form-control-sm'  >
    <% form.label :city, style: "display: block" %>
    <%= form.text_field :city, placeholder: 'City' %>
  </div>
<% current_user %>
<div class = 'form-control-sm'  >
    <% form.label :city, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, type: :hidden %>

  <div class = "btn btn-outline-info " >
    <%= form.submit %>
<% end %>
  </div>
  </div>
  </div>
  </div>
  </div>

app/views/friends/_friend.html.erb
    <table class="table table-striped-columns table-light table-hover table table-bordered">
  <thead  class = 'thead-dark'>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Address</th>
      <th scope="col">Gender</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
    </tr>
  </thead>
  <tbody>


    <% if friend.user == current_user %>
    <tr>
      <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
      <td><%= friend.email %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.address %></td>
      <td><%= friend.gender %></td>
      <td><%= friend.city %></td>
      <td><%= friend.state %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/edit.html.erb
    <div class="card">
    <div class="card-header">
      <h1>Editing friend</h1>

<%= render "form", friend: @friend %>
<%= link_to "Back to friend", friends_path ,class:"btn btn-outline-info btn-sm" %><%= button_to "Delete", @friend, method: :delete, data: {confirm: "Are you sure you want to delete "},class:"btn btn-outline-danger btn-sm bs-btn-font-weight: 100 " %>
<div class="card-body">
 <h5 class="card-title"></h5>
<p class="card-text"></p>
 </div>
</div>
</div>
</div>
</div>
<div>

app/views/friends/index.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<h1>Friends Lists</h1>

<table id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
  <% end %>
</table>

<%= link_to "New friend", new_friend_path, class:"btn btn-outline-info "%>

app/views/friends/new.html.erb
<div class="card">
  <div class="card-header">
<h1> Add New friend</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text"></p>
<%= render "form", friend: @friend %>
<br/>
<div>
  <%= link_to "Back to friend", friends_path,class:"btn btn-outline-info btn-sm"  %>
</div>
</div>
</div>

app/views/friends/show.html.erb
<!-- <p style="color: green"><%= notice %></p>-->
<div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2><%= @friend.first_name%> <%= @friend.last_name %>,</h2>
          <p><%=  @friend.first_name %>  <%= @friend.email %>  <%= @friend.phone %>  <%= @friend.address %>  <%= @friend.state %></p>
<button class="btn btn-outline-light" type="button">
<div>
  <%= link_to "Back to friends", friends_path,class:"btn btn-outline-info btn-sm" %>
  <%= link_to "Edit this friend", edit_friend_path(@friend),class:"btn btn-outline-info btn-sm" %>
  <%= button_to "Delete", @friend, method: :delete, data: {confirm: "Are you sure you want to delete "},class:"btn btn-outline-danger btn-sm bs-btn-font-weight: 100 " %>
</div>
</button>
</div>
</div>

app/views/home/_about.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href="#">Call Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Email</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">message</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Call us today</h5>
    <p class="card-text">We have the best power solution ever</p>
    <a href="#" class="btn btn-primary">Call Now</a>
  </div>
</div>
</body>
</html>

app/views/home/_header.html.erb
<p class = 'welcome_text'>Shop from our different power solutions ranging from Solar, Inverters, Batteries, electtrical Installations etc.</p>

app/views/home/batteries.html.erb
<!DOCTYPE html>
<html>
<head>
<title></title>
 <%= stylesheet_link_tag 'battery' %>
</head>
<body>

<div class="Cart-Container">
<div class=”Header”>
 <h3 class=”Heading”>Shopping Cart</h3>
 <h5 class=”Action”>Remove all</h5>
 </div>
<div class=”Cart-Items”>
 <div class=”image-box”>
 <img src=”images/apple.png” style={{ height=”120px” }} />
 </div>
 <div class=”about”>
 <h1 class=”title”>Wetcell Battery</h1>
 <h3 class=”subtitle”>250ml</h3>
 <%= image_tag ("photos/wetcell.png"), width: "100px" %>
 </div>
 <div class=”counter”></div>
 <div class=”prices”></div>
 </div>

</div>
</body>
</html>

app/views/home/home.html.erb
<!DOCTYPE html>
<head>
<title>Page Title</title>
<meta http-equiv="refresh">
<meta charset="utf-8" content-type="utf-8">
<link href="https://fonts.googleapis.com/css?family=Tangerine">
 <%= stylesheet_link_tag 'home' %>
</head>

    <body>
        <header class = "header">
            <div class = "log-box">
                <%= image_tag("photos/log.JPG",alt:"Log" ,class:"log") %>
            </div>
        <div class = "text-box">
            <h1 class = "heading-primary">
                <span class="heading-primary-main">Elec Solutions</span>
                <span class ="heading-primary-sub">Your One Stop Power Solutions</span>
            </h1>

            <a href ="#" class = "btn btn-white">Discover Our Solutions</a>
            </div>
</header>
    </body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<nav>
  <ul class = "navigation">
  <button><%= link_to "Home", root_path, class: "navbar-brand" %></button>
        <li class="nav-item">
         <%= link_to "BATTERIES", home_batteries_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to "SOLAR", home_solar_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to "INVERTERS", home_inverters_path, class:"navbar-brand" %>
        </li>
       <li class="nav-item">
          <%= link_to "INSTALLATIONS", home_install_path, class:"navbar-brand" %>
        </li>
          <li class="nav-item">
              <%= link_to "INQUIRIES", home_inquire_path, class:"navbar-brand" %>
          </li>
      </ul>

    <div class ="button">
    <%= link_to "LOGIN", elec_solutions_path, class:"btn-login" %>
    </div>

    <div class ="btn-second">
    <%= link_to "SIGN UP", new_elec_solution_path, class:"btn-sign" %>
    </div>



 <form class="search">
      <input class="form" type="search" placeholder="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</nav>

 <div class="col">
<div class="image-haeder">
                <%= image_tag("photos/header.png", alt: "Solar_gen", class:  "header", id: "header_img") %>
</div>
</div>
</body>
</html>

app/views/home/inverters.html.erb
<!DOCTYPE html>
<html>
<head>
<title></title>
  <link rel="stylesheet" href="/sylesheets/application.css">
    <link rel="stylesheet" href="styles.css">
</head>
<body>

<div class=”Cart-Container”></div>
</body>
</html>

app/views/home/signup.html.erb
<!---
<form class="row g-3 needs-validation" novalidate>
  <div class="col-md-4">
    <label for="validationCustom01" class="form-label">First name</label>
    <input type="text" class="form-control" id="validationCustom01" value="Mark" required>
    <div class="valid-feedback">
      Looks good!
    </div>
  </div>

  <div class="col-md-4">
    <label for="validationCustom02" class="form-label">Last name</label>
    <input type="text" class="form-control" id="validationCustom02" value="Otto" required>
    <div class="valid-feedback">
      Looks good!
    </div>
  </div>

  <div class="col-md-4">
    <label for="validationCustomUsername" class="form-label">Username</label>
    <div class="input-group has-validation">
      <span class="input-group-text" id="inputGroupPrepend">@</span>
      <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required>
      <div class="invalid-feedback">
        Please choose a username.
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <label for="validationCustom03" class="form-label">City</label>
    <input type="text" class="form-control" id="validationCustom03" required>
    <div class="invalid-feedback">
      Please provide a valid city.
    </div>
  </div>

  <div class="col-md-3">
    <label for="validationCustom04" class="form-label">State</label>
    <select class="form-select" id="validationCustom04" required>
      <option selected disabled value="">Choose...</option>
      <option>...</option>
    </select>
    <div class="invalid-feedback">
      Please select a valid state.
    </div>
  </div>

  <div class="col-md-3">
    <label for="validationCustom05" class="form-label">Zip</label>
    <input type="text" class="form-control" id="validationCustom05" required>
    <div class="invalid-feedback">
      Please provide a valid zip.
    </div>
  </div>

  <div class="col-12">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
      <label class="form-check-label" for="invalidCheck">
        Agree to terms and conditions
      </label>
      <div class="invalid-feedback">
        You must agree before submitting.
      </div>
    </div>
  </div>
  <div class="col-12">
    <button class="btn btn-primary" type="submit">Submit form</button>
  </div>
</form> -->

app/views/layouts/_message.html.erb
<div class="alert alert-danger" role="alert">
 <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>Elecsolution</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>

 <%  render "home/header" %>
  <%= yield %>

  <% render "home/about" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  </body>
</html>